const { Types } = require("mongoose");

const alumniProfiles = [
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c11111111111111111"),
    college_id: new Types.ObjectId("75c2b2d12222222222222222"),
    full_name: "Arjun Reddy",
    graduation_year: 2018,
    degree: "B.Tech",
    specialization: "Computer Science",
    enrollment_number: "CS2014001",
    current_position: "Software Engineer",
    company: "Microsoft",
    industry: "IT",
    location: "Hyderabad, India",
    professional_achievements: "Published research paper in AI",
    skills: ["JavaScript", "Node.js", "React", "AI"],
    linkedin_url: "https://linkedin.com/in/arjunreddy",
    github_url: "https://github.com/arjunreddy",
    leetcode_url: "https://leetcode.com/arjunreddy",
    contribution_preferences: "Mentoring students in coding",
    about_me: "Passionate about full-stack development.",
    profile_photo_url: "/images/alumni/arjun.jpg",
    contact_number: "9876543210",
    is_verified: true,
    engagement_status: "active",
    prospect_type: "mentor"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c12222222222222222"),
    college_id: new Types.ObjectId("75c2b2d12222222222222222"),
    full_name: "Neha Sharma",
    graduation_year: 2019,
    degree: "B.Tech",
    specialization: "Electronics",
    enrollment_number: "EC2015002",
    current_position: "Hardware Engineer",
    company: "Intel",
    industry: "Semiconductors",
    location: "Bangalore, India",
    professional_achievements: "Best Innovator Award at Intel 2022",
    skills: ["VLSI", "Verilog", "Circuit Design"],
    linkedin_url: "https://linkedin.com/in/nehasharma",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Conducting workshops",
    about_me: "Loves designing chips and circuits.",
    profile_photo_url: "/images/alumni/neha.jpg",
    contact_number: "9876501234",
    is_verified: true,
    engagement_status: "recently_connected",
    prospect_type: "speaker"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c13333333333333333"),
    college_id: new Types.ObjectId("75c2b2d13333333333333333"),
    full_name: "Ravi Kumar",
    graduation_year: 2017,
    degree: "MBA",
    specialization: "Finance",
    enrollment_number: "MBA2013003",
    current_position: "Investment Banker",
    company: "Goldman Sachs",
    industry: "Finance",
    location: "Mumbai, India",
    professional_achievements: "Handled IPOs of multiple startups",
    skills: ["Financial Analysis", "Valuations", "Excel"],
    linkedin_url: "https://linkedin.com/in/ravikumar",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Guiding students on finance careers",
    about_me: "Finance enthusiast and mentor.",
    profile_photo_url: "/images/alumni/ravi.jpg",
    contact_number: "9123456780",
    is_verified: true,
    engagement_status: "active",
    prospect_type: "mentor"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c14444444444444444"),
    college_id: new Types.ObjectId("75c2b2d12222222222222222"),
    full_name: "Sneha Patel",
    graduation_year: 2020,
    degree: "B.Sc",
    specialization: "Biotechnology",
    enrollment_number: "BT2016004",
    current_position: "Research Scientist",
    company: "Novartis",
    industry: "Pharmaceuticals",
    location: "Pune, India",
    professional_achievements: "Published paper in genetic engineering",
    skills: ["Molecular Biology", "Research Writing"],
    linkedin_url: "https://linkedin.com/in/snehapatel",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Donating for research projects",
    about_me: "Biotech researcher passionate about genetics.",
    profile_photo_url: "/images/alumni/sneha.jpg",
    contact_number: "9988776655",
    is_verified: false,
    engagement_status: "inactive",
    prospect_type: "donor"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c15555555555555555"),
    college_id: new Types.ObjectId("75c2b2d14444444444444444"),
    full_name: "Amit Verma",
    graduation_year: 2015,
    degree: "B.Tech",
    specialization: "Mechanical Engineering",
    enrollment_number: "ME2011005",
    current_position: "Automobile Designer",
    company: "Tesla",
    industry: "Automobile",
    location: "California, USA",
    professional_achievements: "Designed energy-efficient car models",
    skills: ["CAD", "SolidWorks", "EV Design"],
    linkedin_url: "https://linkedin.com/in/amitverma",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Guest lectures on automotive design",
    about_me: "Engineer with a vision for sustainable transport.",
    profile_photo_url: "/images/alumni/amit.jpg",
    contact_number: "9876549876",
    is_verified: true,
    engagement_status: "active",
    prospect_type: "speaker"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c16666666666666666"),
    college_id: new Types.ObjectId("75c2b2d15555555555555555"),
    full_name: "Pooja Iyer",
    graduation_year: 2016,
    degree: "B.Tech",
    specialization: "Information Technology",
    enrollment_number: "IT2012006",
    current_position: "Cloud Architect",
    company: "Amazon AWS",
    industry: "Cloud Computing",
    location: "Seattle, USA",
    professional_achievements: "Designed scalable cloud solutions",
    skills: ["AWS", "Azure", "DevOps"],
    linkedin_url: "https://linkedin.com/in/poojaiyer",
    github_url: "https://github.com/poojaiyer",
    leetcode_url: "https://leetcode.com/poojaiyer",
    contribution_preferences: "Mentoring students on cloud computing",
    about_me: "Helping businesses migrate to the cloud.",
    profile_photo_url: "/images/alumni/pooja.jpg",
    contact_number: "9876123450",
    is_verified: true,
    engagement_status: "recently_connected",
    prospect_type: "mentor"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c17777777777777777"),
    college_id: new Types.ObjectId("75c2b2d16666666666666666"),
    full_name: "Karan Singh",
    graduation_year: 2014,
    degree: "B.Tech",
    specialization: "Civil Engineering",
    enrollment_number: "CE2010007",
    current_position: "Structural Engineer",
    company: "L&T Construction",
    industry: "Infrastructure",
    location: "Delhi, India",
    professional_achievements: "Led metro rail bridge projects",
    skills: ["AutoCAD", "Structural Analysis"],
    linkedin_url: "https://linkedin.com/in/karansingh",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Mentoring on civil projects",
    about_me: "Engineer passionate about sustainable structures.",
    profile_photo_url: "/images/alumni/karan.jpg",
    contact_number: "9765432109",
    is_verified: true,
    engagement_status: "active",
    prospect_type: "mentor"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c18888888888888888"),
    college_id: new Types.ObjectId("75c2b2d12222222222222222"),
    full_name: "Ritika Malhotra",
    graduation_year: 2021,
    degree: "BBA",
    specialization: "Marketing",
    enrollment_number: "BBA2017008",
    current_position: "Marketing Manager",
    company: "Unilever",
    industry: "FMCG",
    location: "Gurgaon, India",
    professional_achievements: "Launched digital campaigns with high ROI",
    skills: ["Digital Marketing", "SEO", "Brand Strategy"],
    linkedin_url: "https://linkedin.com/in/ritikamalhotra",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Organizing career guidance sessions",
    about_me: "Marketer focused on brand growth.",
    profile_photo_url: "/images/alumni/ritika.jpg",
    contact_number: "9812345678",
    is_verified: true,
    engagement_status: "active",
    prospect_type: "speaker"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c19999999999999999"),
    college_id: new Types.ObjectId("75c2b2d17777777777777777"),
    full_name: "Ankit Deshmukh",
    graduation_year: 2013,
    degree: "B.Tech",
    specialization: "Electrical Engineering",
    enrollment_number: "EE2009009",
    current_position: "Energy Consultant",
    company: "Siemens",
    industry: "Energy",
    location: "Berlin, Germany",
    professional_achievements: "Worked on smart grid solutions",
    skills: ["Power Systems", "Renewable Energy"],
    linkedin_url: "https://linkedin.com/in/ankitdeshmukh",
    github_url: "",
    leetcode_url: "",
    contribution_preferences: "Donating for renewable projects",
    about_me: "Passionate about clean energy.",
    profile_photo_url: "/images/alumni/ankit.jpg",
    contact_number: "9098765432",
    is_verified: false,
    engagement_status: "inactive",
    prospect_type: "donor"
  },
  {
    _id: new Types.ObjectId(),
    user_id: new Types.ObjectId("65b1a1c1aaaaaaaaaaaaaaaa"),
    college_id: new Types.ObjectId("75c2b2d18888888888888888"),
    full_name: "Meera Krishnan",
    graduation_year: 2012,
    degree: "M.Tech",
    specialization: "Artificial Intelligence",
    enrollment_number: "AI2008010",
    current_position: "AI Researcher",
    company: "Google DeepMind",
    industry: "AI",
    location: "London, UK",
    professional_achievements: "Developed cutting-edge AI algorithms",
    skills: ["Machine Learning", "Deep Learning", "Python"],
    linkedin_url: "https://linkedin.com/in/meerakrishnan",
    github_url: "https://github.com/meerakrishnan",
    leetcode_url: "https://leetcode.com/meerakrishnan",
    contribution_preferences: "Mentoring & donations",
    about_me: "AI researcher with 10+ years experience.",
    profile_photo_url: "/images/alumni/meera.jpg",
    contact_number: "9012345678",
    is_verified: true,
    engagement_status: "active",
    prospect_type: "mentor"
  }
];

module.exports = alumniProfiles;
