const { Types } = require("mongoose");

// Example Users (10 unique users)
const userIds = [
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId(),
  new Types.ObjectId()
];

const studentProfiles = [
  {
    _id: new Types.ObjectId(),
    user_id: userIds[0],
    full_name: "Raja Reddy",
    enrollment_number: "CSE2025001",
    course: "B.Tech",
    branch: "CSE",
    year_of_admission: 2022,
    year_of_graduation: 2026,
    contact_number: "9876543210",
    address: "Hyderabad, India",
    skills: ["Java", "Python", "Machine Learning"],
    interests: ["AI", "Web Development"],
    career_goals: "Software Engineer",
    discovery_insights: "Interested in ML research",
    preferences: "Mentorship in AI projects",
    photo: "",
    linkedin: "https://linkedin.com/in/raja-reddy",
    github: "https://github.com/raja-reddy",
    portfolio: "https://raja-reddy.com",
    extracuriculum: "Coding Club, Robotics",
    is_verified: true
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[1],
    full_name: "Sneha Sharma",
    enrollment_number: "ECE2025002",
    course: "B.Tech",
    branch: "ECE",
    year_of_admission: 2021,
    year_of_graduation: 2025,
    contact_number: "9123456780",
    address: "Bangalore, India",
    skills: ["Embedded Systems", "C", "IoT"],
    interests: ["Robotics", "Hardware Design"],
    career_goals: "IoT Developer",
    discovery_insights: "Focused on embedded systems",
    preferences: "Mentorship in hardware projects",
    photo: "",
    linkedin: "https://linkedin.com/in/sneha-sharma",
    github: "https://github.com/sneha-sharma",
    portfolio: "https://sneha-sharma.com",
    extracuriculum: "Electronics Club",
    is_verified: true
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[2],
    full_name: "Arjun Patel",
    enrollment_number: "ME2025003",
    course: "B.Tech",
    branch: "Mechanical",
    year_of_admission: 2020,
    year_of_graduation: 2024,
    contact_number: "9988776655",
    address: "Mumbai, India",
    skills: ["CAD", "Robotics"],
    interests: ["Automation", "Design"],
    career_goals: "Mechanical Engineer",
    discovery_insights: "Interested in CAD modeling",
    preferences: "Mentorship in mechanical design",
    photo: "",
    linkedin: "https://linkedin.com/in/arjun-patel",
    github: "https://github.com/arjun-patel",
    portfolio: "https://arjun-patel.com",
    extracuriculum: "Robotics Club",
    is_verified: false
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[3],
    full_name: "Meera Iyer",
    enrollment_number: "CSE2025004",
    course: "B.Tech",
    branch: "CSE",
    year_of_admission: 2022,
    year_of_graduation: 2026,
    contact_number: "9012345678",
    address: "Chennai, India",
    skills: ["Python", "Web Development"],
    interests: ["Frontend", "UI/UX"],
    career_goals: "Full Stack Developer",
    discovery_insights: "Interested in web technologies",
    preferences: "Mentorship in web development",
    photo: "",
    linkedin: "https://linkedin.com/in/meera-iyer",
    github: "https://github.com/meera-iyer",
    portfolio: "https://meera-iyer.com",
    extracuriculum: "Coding Club",
    is_verified: true
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[4],
    full_name: "Karan Verma",
    enrollment_number: "EE2025005",
    course: "B.Tech",
    branch: "Electrical",
    year_of_admission: 2021,
    year_of_graduation: 2025,
    contact_number: "9234567890",
    address: "Delhi, India",
    skills: ["Power Systems", "MATLAB"],
    interests: ["Renewable Energy", "Circuits"],
    career_goals: "Electrical Engineer",
    discovery_insights: "Focused on renewable systems",
    preferences: "Mentorship in electrical projects",
    photo: "",
    linkedin: "https://linkedin.com/in/karan-verma",
    github: "https://github.com/karan-verma",
    portfolio: "https://karan-verma.com",
    extracuriculum: "Energy Club",
    is_verified: true
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[5],
    full_name: "Ananya Gupta",
    enrollment_number: "CSE2025006",
    course: "B.Tech",
    branch: "CSE",
    year_of_admission: 2023,
    year_of_graduation: 2027,
    contact_number: "9123987654",
    address: "Pune, India",
    skills: ["JavaScript", "React", "Node.js"],
    interests: ["Web Apps", "UI/UX Design"],
    career_goals: "Frontend Developer",
    discovery_insights: "Interested in interactive web apps",
    preferences: "Mentorship in React projects",
    photo: "",
    linkedin: "https://linkedin.com/in/ananya-gupta",
    github: "https://github.com/ananya-gupta",
    portfolio: "https://ananya-gupta.com",
    extracuriculum: "Coding Club",
    is_verified: false
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[6],
    full_name: "Vikram Singh",
    enrollment_number: "ME2025007",
    course: "B.Tech",
    branch: "Mechanical",
    year_of_admission: 2020,
    year_of_graduation: 2024,
    contact_number: "9876123450",
    address: "Jaipur, India",
    skills: ["SolidWorks", "Thermodynamics"],
    interests: ["Automobile Design", "Robotics"],
    career_goals: "Mechanical Engineer",
    discovery_insights: "Focused on CAD and robotics",
    preferences: "Mentorship in automotive projects",
    photo: "",
    linkedin: "https://linkedin.com/in/vikram-singh",
    github: "https://github.com/vikram-singh",
    portfolio: "https://vikram-singh.com",
    extracuriculum: "Robotics Club",
    is_verified: true
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[7],
    full_name: "Priya Ramesh",
    enrollment_number: "ECE2025008",
    course: "B.Tech",
    branch: "ECE",
    year_of_admission: 2022,
    year_of_graduation: 2026,
    contact_number: "9012456789",
    address: "Kolkata, India",
    skills: ["VLSI", "Digital Design"],
    interests: ["Chips Design", "Robotics"],
    career_goals: "VLSI Engineer",
    discovery_insights: "Interested in IC design",
    preferences: "Mentorship in VLSI projects",
    photo: "",
    linkedin: "https://linkedin.com/in/priya-ramesh",
    github: "https://github.com/priya-ramesh",
    portfolio: "https://priya-ramesh.com",
    extracuriculum: "Electronics Club",
    is_verified: true
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[8],
    full_name: "Rohan Mehta",
    enrollment_number: "CSE2025009",
    course: "B.Tech",
    branch: "CSE",
    year_of_admission: 2023,
    year_of_graduation: 2027,
    contact_number: "9988123456",
    address: "Mumbai, India",
    skills: ["Python", "Django", "Data Science"],
    interests: ["ML", "Web Development"],
    career_goals: "Data Scientist",
    discovery_insights: "Focused on ML projects",
    preferences: "Mentorship in Data Science",
    photo: "",
    linkedin: "https://linkedin.com/in/rohan-mehta",
    github: "https://github.com/rohan-mehta",
    portfolio: "https://rohan-mehta.com",
    extracuriculum: "Data Club",
    is_verified: false
  },
  {
    _id: new Types.ObjectId(),
    user_id: userIds[9],
    full_name: "Sakshi Jain",
    enrollment_number: "EE2025010",
    course: "B.Tech",
    branch: "Electrical",
    year_of_admission: 2021,
    year_of_graduation: 2025,
    contact_number: "9123765890",
    address: "Delhi, India",
    skills: ["Power Systems", "MATLAB"],
    interests: ["Renewable Energy", "Smart Grids"],
    career_goals: "Electrical Engineer",
    discovery_insights: "Interested in power optimization",
    preferences: "Mentorship in electrical systems",
    photo: "",
    linkedin: "https://linkedin.com/in/sakshi-jain",
    github: "https://github.com/sakshi-jain",
    portfolio: "https://sakshi-jain.com",
    extracuriculum: "Energy Club",
    is_verified: true
  }
];

module.exports = studentProfiles;
